name: 'Coveralls GitHub Action'

on: ["push", "pull_request"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: install dependencies
        run: npm install
      - name: run test
        run: npm run test:coveralls
        env: 
          COVERALLS_REPO_TOKEN: ${{ secrets.REPO_TOKEN }}